import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App", // Allows page-specific titles to append
  },
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    url: "https://demonext-tan.vercel.app/",
    siteName: "Create Next App",
    images: [
      {
        url: "https://yourdomain.com/images/default-og-image.jpg", // Fallback image
        width: 1200,
        height: 630,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}